version: '3'
services:
  echo:
    build: echo
    container_name: echo
    tty: true
    volumes:
      - ".:/go/src/app"
      - "/go/src/app/vendor"
    ports:
      - "8080:8080"
  chi:
    build: chi
    container_name: chi
    volumes:
      - ".:/go/src/app"
      - "/go/src/app/vendor"
    ports:
      - "8081:8081"